services:
  trainer-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5201:50051" 
    environment:
      - MongoDB__ConnectionString=mongodb://admin:password@mongodb:27017
      - MongoDB__DatabaseName=Pokedex
      - MongoDB__TrainerCollectionName=trainers
    depends_on:
      - mongodb
    networks:
      - trainer-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db
    networks:
      - trainer-network

networks:
  trainer-network:
    driver: bridge

volumes:
  mongodb-data:
